name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8be72c92abb1b122b7c545d2d3327bf549296b51657e47d933042a67c08ab009"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
