name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c02adef6cd69e12b0974bcbfbb85663f2079163395648e763b69b29be4456018"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
