name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b220fb89bc2d25324e852b2e1c239c1909eabc46b060da3b5d8581d5320ac18"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
