name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb5841e761ede5ca26884ed9742ae53c316a562c92cd096da04084e2c3dd81c4"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
