name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c8c9e8567ed751b249d424f57f505199d0ed69a31da944bdee1f5a1567388ab"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
