name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf199424d2e5ce33e20cf3c1bb69ff6e9ac3b2ff9c8bb013af3aea09ef86648d"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
