name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d4e156c2234d35656b16cd73f60d9359961a5432fdad57d48bc61ab60b63c09"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
