name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e337b569d38647a25c92b8bff3ca968b16925c06f56d229967698f7ba8e3e33f"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
