name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98313741b2bbe5f599aea70aa867f544cee13f87de06fd2c5151728d1f878472"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
