name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b05f9d68ce6941e8af1d86a4b39aa0b20f87e042202bc85338537eea4411f34"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
