name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2455fb622efa086f27a3ac8b1776670c6bb318482eeb9d8977a38eb46ec190dd"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
