name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3190f2cd0bcefb1dd9de131b16214da7250ff472450934ba782b8a076cd2fef1"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
