name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "595403349167e5c273f7f24e7b64326b3b7eb02463b18bd28b2dea84c63dc9ac"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
