name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b73a0c2933dee1a86796b9daa2813dd2535cca88cfb351a5cd40613c162d2df2"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
