name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6343e7465bba179dad5dbad17d572f7c4a16f1ecf60983dd063b338d430db3d"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
