name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b9c45f12535a1d3dac40eab9527c752878cfaed7865b5cca47f80a72a3d6810"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
