name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c73e6831b2506813045cef22c74fead0b64b1f4cf867b9ac58cdbf3e4638db3"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
