name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4d8b974000f7f1884d66c5e25f14ab29b5cd09a169b2cc543e06b18fd54cc80"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
