name = "Mc Moon World"
author = "moondane"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82284b53172cbfe64873400346db94ebbfe6c2f735d9fb89d68938c92cd8a38d"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
