name = "Architectury API (Fabric)"
filename = "architectury-3.7.26.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/162/architectury-3.7.26.jar"
hash-format = "murmur2"
hash = "263035498"

[update]
[update.curseforge]
file-id = 3666162
project-id = 419697
