name = "Architectury API (Fabric)"
filename = "architectury-3.7.31.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/604/architectury-3.7.31.jar"
hash-format = "murmur2"
hash = "3281503251"

[update]
[update.curseforge]
file-id = 3671604
project-id = 419697
