name = "Basic Shields [Fabric]"
filename = "BasicShields-1.2.1-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3594/300/BasicShields-1.2.1-1.18.1.jar"
hash-format = "murmur2"
hash = "3694096316"

[update]
[update.curseforge]
file-id = 3594300
project-id = 538011
