name = "[Fabric] Expanded Storage"
filename = "expandedstorage-7.3.10+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/60/expandedstorage-7.3.10+1.18.1.jar"
hash-format = "murmur2"
hash = "2033030455"

[update]
[update.curseforge]
file-id = 3666060
project-id = 317856
