name = "Fabric Shield Lib"
filename = "FabricShieldLib-1.5.2-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/171/FabricShieldLib-1.5.2-1.18.jar"
hash-format = "murmur2"
hash = "4130460008"

[update]
[update.curseforge]
file-id = 3671171
project-id = 380649
