name = "Fabric Shield Lib"
filename = "FabricShieldLib-1.5.0-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3637/448/FabricShieldLib-1.5.0-1.18.jar"
hash-format = "murmur2"
hash = "4072106138"

[update]
[update.curseforge]
file-id = 3637448
project-id = 380649
