name = "Fabric API"
filename = "fabric-api-0.46.6+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/143/fabric-api-0.46.6+1.18.jar"
hash-format = "murmur2"
hash = "2482149989"

[update]
[update.curseforge]
file-id = 3671143
project-id = 306612
