name = "The Guild"
filename = "guild-fabric-0.3.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3600/139/guild-fabric-0.3.8.jar"
hash-format = "murmur2"
hash = "3785691119"

[update]
[update.curseforge]
file-id = 3600139
project-id = 526011
