name = "NinjaPhenix's Container Library"
filename = "ninjaphenix-container-library-1.3.0+1.18-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3649/305/ninjaphenix-container-library-1.3.0+1.18-fabric.jar"
hash-format = "murmur2"
hash = "4158358729"

[update]
[update.curseforge]
file-id = 3649305
project-id = 530668
