name = "Quartz Elevator"
filename = "quartz-elevator-2.1.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3614/704/quartz-elevator-2.1.0+1.18.jar"
hash-format = "murmur2"
hash = "1196542242"

[update]
[update.curseforge]
file-id = 3614704
project-id = 442509
