name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-7.3.435.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/906/RoughlyEnoughItems-7.3.435.jar"
hash-format = "murmur2"
hash = "1653255522"

[update]
[update.curseforge]
file-id = 3666906
project-id = 310111
