name = "Void Totem (Fabric)"
filename = "voidtotem-fabric-1.18.1-1.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3646/159/voidtotem-fabric-1.18.1-1.1.2.jar"
hash-format = "murmur2"
hash = "1009593903"

[update]
[update.curseforge]
file-id = 3646159
project-id = 456137
