name = "Xaero's Minimap"
filename = "Xaeros_Minimap_22.1.1_Fabric_1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3626/663/Xaeros_Minimap_22.1.1_Fabric_1.18.jar"
hash-format = "murmur2"
hash = "698793341"

[update]
[update.curseforge]
file-id = 3626663
project-id = 263420
